<?php
// Redirect to the database stage if the DB details are not in the session.
if (empty($_SESSION['db_host'])) {
    header('Location: index.php?stage=database');
    exit;
}

$error = null;

// Function to import the SQL schema.
function import_schema($mysqli, $file) {
    $sql = file_get_contents($file);
    if ($sql === false) {
        return false;
    }
    // Execute the multi-query
    if ($mysqli->multi_query($sql)) {
        // It's important to clear the results of a multi_query.
        while ($mysqli->next_result()) {
            if (!$mysqli->more_results()) break;
        }
        return true;
    }
    return false;
}

// Establish the database connection using session details.
$mysqli = new mysqli($_SESSION['db_host'], $_SESSION['db_user'], $_SESSION['db_pass'], $_SESSION['db_name']);

// Handle the form submission for creating the admin account.
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $admin_user = trim($_POST['admin_user']);
    $admin_email = trim($_POST['admin_email']);
    $admin_pass = $_POST['admin_pass'];

    // First, import the database schema.
    if (!import_schema($mysqli, 'schema.sql')) {
        $error = "Error importing database schema: " . $mysqli->error;
    } else {
        // Schema imported successfully, now create the admin user.
        $hashed_password = password_hash($admin_pass, PASSWORD_DEFAULT);
        $stmt = $mysqli->prepare("INSERT INTO users (username, email, password, is_admin) VALUES (?, ?, ?, 1)");

        if ($stmt) {
            $stmt->bind_param('sss', $admin_user, $admin_email, $hashed_password);
            if ($stmt->execute()) {
                // Admin account created. Now, create the config.php file.
                $config_content = "<?php\n\n";
                $config_content .= "/**\n * Database Configuration\n * \n * This file is automatically generated by the installer.\n * Do not edit this file directly.\n */\n\n";
                $config_content .= "define('DB_HOST', '" . addslashes($_SESSION['db_host']) . "');\n";
                $config_content .= "define('DB_USER', '" . addslashes($_SESSION['db_user']) . "');\n";
                $config_content .= "define('DB_PASS', '" . addslashes($_SESSION['db_pass']) . "');\n";
                $config_content .= "define('DB_NAME', '" . addslashes($_SESSION['db_name']) . "');\n";

                // Write the config file to the 'includes' directory.
                if (file_put_contents('../includes/config.php', $config_content)) {
                    // Success! Redirect to the final stage.
                    header('Location: index.php?stage=complete');
                    exit;
                } else {
                    $error = "Fatal Error: Could not write the configuration file. Please check file permissions on the /includes/ directory.";
                }

            } else {
                $error = "Failed to create admin account: " . $stmt->error;
            }
            $stmt->close();
        } else {
            $error = "Failed to prepare statement for admin creation: " . $mysqli->error;
        }
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Installer - Admin Setup</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <div class="card">
            <div class="card-header">
                <h2>Create Admin Account</h2>
            </div>
            <div class="card-body">
                <?php if ($error): ?>
                    <div class="alert alert-danger"><?php echo $error; ?></div>
                <?php endif; ?>

                <p>The database schema will be imported, and your primary admin account will be created.</p>

                <form method="POST">
                    <div class="mb-3">
                        <label for="admin_user" class="form-label">Admin Username</label>
                        <input type="text" class="form-control" id="admin_user" name="admin_user" required>
                    </div>
                    <div class="mb-3">
                        <label for="admin_email" class="form-label">Admin Email</label>
                        <input type="email" class="form-control" id="admin_email" name="admin_email" required>
                    </div>
                    <div class="mb-3">
                        <label for="admin_pass" class="form-label">Admin Password</label>
                        <input type="password" class="form-control" id="admin_pass" name="admin_pass" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Create Account & Finish Installation</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>