<?php
session_start();
header('Content-Type: application/json');

// --- Security Checks ---
// 1. Check if this is a POST request
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['success' => false, 'message' => 'Invalid request method.']);
    exit;
}

// 2. Check if installer is already locked
if (file_exists('../../install.lock')) {
    echo json_encode(['success' => false, 'message' => 'Installer is locked. Please delete install.lock to run the installer again.']);
    exit;
}

// 3. Check if all required session data is present
if (!isset($_SESSION['db_credentials']) || !isset($_SESSION['site_details'])) {
    echo json_encode(['success' => false, 'message' => 'Session data is missing. Please start the installation from step 1.']);
    exit;
}

// --- Installation Process ---
$db_creds = $_SESSION['db_credentials'];
$site_details = $_SESSION['site_details'];

// Step 1: Create the config.php file
$config_content = "<?php
// Auto-generated by installer

// -- Database Configuration --
define('DB_HOST', '{$db_creds['host']}');
define('DB_NAME', '{$db_creds['name']}');
define('DB_USER', '{$db_creds['user']}');
define('DB_PASS', '{$db_creds['pass']}');

// -- Site Settings --
define('SITE_NAME', '{$site_details['site_name']}');
define('SITE_URL', (isset(\$_SERVER['HTTPS']) && \$_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . \$_SERVER['HTTP_HOST']);

// -- Security --
define('SECRET_KEY', bin2hex(random_bytes(32))); // For sessions, tokens, etc.
";

$config_path = '../../config.php';
if (file_put_contents($config_path, $config_content) === false) {
    echo json_encode(['success' => false, 'message' => 'Error: Could not write to config.php. Please check file permissions.']);
    exit;
}

// Step 2: Connect to the database and import the schema
$mysqli = @new mysqli($db_creds['host'], $db_creds['user'], $db_creds['pass'], $db_creds['name']);
if ($mysqli->connect_error) {
    unlink($config_path); // Clean up failed install
    echo json_encode(['success' => false, 'message' => 'Database connection failed: ' . $mysqli->connect_error]);
    exit;
}

$schema_path = '../schema.sql';
if (!file_exists($schema_path)) {
    unlink($config_path); // Clean up
    echo json_encode(['success' => false, 'message' => 'Error: schema.sql not found.']);
    exit;
}
$sql = file_get_contents($schema_path);
if ($mysqli->multi_query($sql) === false) {
    unlink($config_path); // Clean up
    echo json_encode(['success' => false, 'message' => 'Error importing database schema: ' . $mysqli->error]);
    exit;
}
// Clear results from multi_query
while ($mysqli->next_result()) {
    if ($result = $mysqli->store_result()) {
        $result->free();
    }
}


// Step 3: Insert the admin user
$username = $mysqli->real_escape_string($site_details['admin_username']);
$email = $mysqli->real_escape_string($site_details['admin_email']);
$password_hash = password_hash($site_details['admin_password'], PASSWORD_DEFAULT);

$insert_admin_sql = "INSERT INTO users (username, email, password, role) VALUES ('{$username}', '{$email}', '{$password_hash}', 'admin')";

if ($mysqli->query($insert_admin_sql) === false) {
    unlink($config_path); // Clean up
    echo json_encode(['success' => false, 'message' => 'Error creating admin user: ' . $mysqli->error]);
    exit;
}

$mysqli->close();

// Step 4: Create the lock file
if (file_put_contents('../../install.lock', 'Installation completed on ' . date('Y-m-d H:i:s')) === false) {
     // This is not a fatal error, but we should warn the user.
    echo json_encode(['success' => true, 'message' => 'Installation successful, but failed to create the lock file. Please create an empty file named "install.lock" in the root directory manually for security.']);
    exit;
}

// Step 5: Clean up session and respond
session_destroy();
echo json_encode(['success' => true, 'message' => 'Installation completed successfully!']);
exit;