<?php
// Stage 3: Database Installation & Config Creation

// --- 1. Get DB details from session ---
if (!isset($_SESSION['db_details'])) {
    header('Location: install.php?stage=2');
    exit;
}
$db = $_SESSION['db_details'];

// --- 2. Test Database Connection ---
@$conn = new mysqli($db['host'], $db['user'], $db['pass'], $db['name']);

if ($conn->connect_error) {
    $_SESSION['db_error'] = "Connection Failed: " . $conn->connect_error;
    header('Location: install.php?stage=2');
    exit;
}

$install_success = false;
$config_success = false;
$error = null;

// --- 3. Execute SQL from database.sql ---
$sql_file_path = __DIR__ . '/../database.sql';
if (!file_exists($sql_file_path)) {
    $error = "The `database.sql` file could not be found. Installation cannot continue.";
} else {
    $sql_content = file_get_contents($sql_file_path);
    if ($conn->multi_query($sql_content)) {
        do {
            if ($result = $conn->store_result()) {
                $result->free();
            }
        } while ($conn->more_results() && $conn->next_result());

        $new_admin_password = 'password123';
        $hashed_password = password_hash($new_admin_password, PASSWORD_DEFAULT);

        $update_stmt = $conn->prepare("UPDATE users SET password_hash = ? WHERE user_id = 1");
        $update_stmt->bind_param("s", $hashed_password);
        $update_stmt->execute();
        $update_stmt->close();

        $install_success = true;

    } else {
        $error = "An error occurred during database setup: " . $conn->error;
    }
}

// --- 4. Create the config.php file ---
if ($install_success) {
    $config_template = <<<EOT
<?php
// =================================================================
// CBT PLATFORM CONFIGURATION FILE
// Generated by the installer on " . date("Y-m-d H:i:s") . "
// =================================================================

// --- PHP Session Start ---
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

// --- Error Reporting ---
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// --- Database Credentials ---
define('DB_HOST', '{$db['host']}');
define('DB_USER', '{$db['user']}');
define('DB_PASS', '{$db['pass']}');
define('DB_NAME', '{$db['name']}');

// --- Site Configuration ---
define('SITE_NAME', 'CBT Platform');
// Dynamically determine the base URL
\$protocol = (!empty(\$_SERVER['HTTPS']) && \$_SERVER['HTTPS'] !== 'off' || \$_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
\$host = \$_SERVER['HTTP_HOST'];
define('BASE_URL', \$protocol . \$host . '/');

// --- Create Database Connection using MySQLi ---
\$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);

// --- Check Connection ---
if (\$conn->connect_error) {
    die("Database Connection Failed: " . \$conn->connect_error);
}

// --- Set Character Set ---
if (!\$conn->set_charset("utf8mb4")) {
    printf("Error loading character set utf8mb4: %s\n", \$conn->error);
    exit();
}

?>
EOT;

    $config_path = __DIR__ . '/../includes/config.php';
    if (!file_put_contents($config_path, $config_template)) {
        $error = "Could not write to `includes/config.php`. Please check file permissions.";
    } else {
        $config_success = true;
    }
}

$conn->close();

// --- 5. Advance to next stage or show error ---
if ($install_success && $config_success) {
    $_SESSION['install_stage'] = 4;
    header('Location: install.php?stage=4');
    exit;
}

// If we reach here, an error must have occurred.
$pageTitle = "Stage 3: Installation Error";

?>

<h1>Stage 3: Installation Error</h1>
<hr>

<div class="alert alert-danger">
    <strong>An error occurred:</strong><br>
    <?php echo htmlspecialchars($error ?? 'An unknown error occurred. Please try again.'); ?>
</div>
<div style="margin-top: 20px;">
    <a href="install.php?stage=2" class="btn" style="background-color: #6c757d;">&laquo; Back to Database Setup</a>
</div>
