<?php
/**
 * Database Connector
 *
 * This file establishes the connection to the MySQL database.
 * It depends on a config.php file (generated by the installer) for credentials.
 */

// Use require_once to ensure the config file is loaded only once.
// The __DIR__ constant provides an absolute path for reliability.
require_once __DIR__ . '/config.php';

// Create a new MySQLi object to connect to the database.
$mysqli = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);

// Check for and handle connection errors.
if ($mysqli->connect_error) {
    // In a production environment, you should log this error instead of displaying it.
    die('Database connection failed: ' . $mysqli->connect_error);
}

// Set the character set to utf8mb4 to ensure full Unicode support.
$mysqli->set_charset('utf8mb4');
?>